"""
FinResolve AI — Evidence Collector

Aggregates, deduplicates, and structures evidence items produced by matching
evaluations and reconciliation rule executions.
"""

from __future__ import annotations

from data.schemas.evidence import Evidence, Severity
from services.reconciliation.rules.base import RuleResult


class EvidenceCollector:
    """
    Stateful evidence collection and filtering utility for a reconciliation case.
    """

    def __init__(self):
        self._evidence: list[Evidence] = []
        self._seen_keys: set[str] = set()

    def add_evidence(self, item: Evidence) -> None:
        """Add an evidence item if not a duplicate."""
        key = f"{item.source_record_id}:{item.field_name}:{item.evidence_type.value}:{item.observed_value}"
        if key not in self._seen_keys:
            self._seen_keys.add(key)
            self._evidence.append(item)

    def collect_from_rule_results(self, rule_results: list[RuleResult]) -> list[Evidence]:
        """Extract and aggregate all evidence items generated by rule evaluations."""
        for result in rule_results:
            for item in result.evidence_items:
                self.add_evidence(item)
        return list(self._evidence)

    def get_all(self) -> list[Evidence]:
        """Return all collected evidence items."""
        return list(self._evidence)

    def get_by_severity(self, min_severity: Severity = Severity.LOW) -> list[Evidence]:
        """Filter evidence by minimum severity level."""
        severity_order = {
            Severity.INFO: 0,
            Severity.LOW: 1,
            Severity.MEDIUM: 2,
            Severity.HIGH: 3,
            Severity.CRITICAL: 4,
        }
        min_level = severity_order.get(min_severity, 0)
        return [e for e in self._evidence if severity_order.get(e.severity, 0) >= min_level]
