"""
FinResolve AI — Base Reconciliation Rule & Rule Result

Defines the contract for deterministic reconciliation rules.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field

from data.schemas.evidence import Evidence, Severity
from data.schemas.matching import MatchGroup


class RuleResult(BaseModel):
    """
    Structured outcome of evaluating a reconciliation rule against a matched group of records.
    """

    rule_id: str = Field(description="Unique rule identifier (e.g. 'RULE-AMT-001')")
    category: str = Field(description="Rule category (e.g. 'amount', 'fee', 'temporal', 'status', 'ledger')")
    passed: bool = Field(description="Whether the rule passed without discrepancy")
    severity: Severity = Field(default=Severity.INFO, description="Severity if rule failed")
    
    # Financial arithmetic trail in integer minor units
    expected_value: Any | None = Field(default=None, description="Expected value or breakdown")
    observed_value: Any | None = Field(default=None, description="Observed value or breakdown")
    difference: Any | None = Field(default=None, description="Exact discrepancy delta if applicable")
    
    evidence_items: list[Evidence] = Field(default_factory=list, description="Evidence generated by this rule")
    explanation: str = Field(description="Human and machine-readable explanation of the evaluation")

    model_config = {"from_attributes": True}


class BaseReconciliationRule(ABC):
    """
    Abstract base class for all deterministic reconciliation rules.
    """

    rule_id: str
    category: str

    @abstractmethod
    def evaluate(
        self,
        group: MatchGroup,
        records_lookup: dict[str, dict[str, Any]],
    ) -> RuleResult:
        """
        Evaluate the rule on a matched record group.

        Args:
            group: The matched group under evaluation.
            records_lookup: Lookup table mapping 'record_id' to full raw/canonical record dict.

        Returns:
            RuleResult with arithmetic details and generated evidence.
        """
        raise NotImplementedError
